### PR TITLE
block entities servux paste

### PR DESCRIPTION
**Pull request by zly2006**

### CODE REVIEW

**Comment by sakura-ryoko** [comment]
Let me know if you think this is good enough for review.

**Comment by zly2006** [comment]
I did not change a lot on litematica, currently this works well. review this please, and servux as well

**Comment by sakura-ryoko** [comment]
I found a Servux side issue for this with the Packet Splitter.  It's not a "bug" but it's more of a "we need to allow Packet Splitter to receive larger slices from a Client" issue.

**Comment by sakura-ryoko** [comment]
All set for merge

**Pull request merged**
