### PR TITLE
Korean translation update, minor typos and description correction

### PR DESCRIPTION
**Pull request by MagPlum**
The Korean translation for Litematica has been completed.

I have a few questions.

*About "litematica.config.generic.comment.pasteNbtRestoreBehavior"
1. Does the 'Teleport & Place' option still exist? If it's an outdated feature, should the related comments be preserved?
2. what are 'pasteCommandLimit' and 'pasteCommandInterval' ? Do they mean 'commandLimitPerTick' and 'commandTaskInterval' ?
If it's right, then I think the comment should be revised as follows:
"Whether or not the NBT data of blocks is attempted to be restored,\nand which method is used for that.\n- Place & Data Modify will try to place the \"NBT-picked\" block\n  near the player, and then use the data modify\n  command to transfer the NBT data to the setblock'ed block\n- Place & Clone will try to place the \"NBT-picked\" block\n  near the player, and then clone it to the final location.\nThe recommended method is §ePlace & Data Modify§r, however for that to work\nyou will probably need to lower the commandLimitPerTick to 1 per tick and increase\nthe commandTaskInterval to 1-4 ticks or something.\nThus you should only use this for pasting important blocks that need the data,\nfor example by making a schematic of just the inventories,\nand then paste that with replace behavior set to None.",

*About "litematica.config.generic.comment.commandUseWorldEdit"
Isn't the next part weird?
"if the server doesn't have the Carpet mod and thus the '/carpet fillUpdates false' rule available."
Does this mean the following? or am I just bad at English?
"if the server doesn't have the Carpet mod and thus the '/carpet fillUpdates false' rule inavailable."

### CODE REVIEW

**Comment by sakura-ryoko** [comment]
Generally, I would say if the wording doesn't make a ton of sense, just leave it be.  I think Masa's overall plan is to rewrite everything; because there are old entries, old code; and various things.  I don't think the plan is to "clean it up" either.

**Comment by sakura-ryoko** [comment]
Minor / obvious issues aside of course :)

**Comment by sakura-ryoko** [comment]
Thank you again

**Comment by MagPlum** [comment]
> Generally, I would say if the wording doesn't make a ton of sense, just leave it be. I think Masa's overall plan is to rewrite everything; because there are old entries, old code; and various things. I don't think the plan is to "clean it up" either.

I got it. Thank you very much.

**Pull request merged**
